include: package:pedantic/analysis_options.1.9.0.yaml
linter:
  rules:
    #avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    empty_statements: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_shadowing_type_parameters: true
    avoid_void_async: true
    join_return_with_assignment: true
    list_remove_unrelated_type: true
    always_use_package_imports: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    sized_box_for_whitespace: true
    unnecessary_await_in_return: true
    unnecessary_string_interpolations: true
    prefer_final_locals: true

    lines_longer_than_80_chars: false
    avoid_types_as_parameter_names: false
    use_function_type_syntax_for_parameters: false
    prefer_single_quotes: false
    curly_braces_in_flow_control_structures: false
    always_declare_return_types: false
    library_prefixes: false
    prefer_asserts_with_message: false
analyzer:
  exclude: [build/**, test/**, lib/**/*.g.dart]
  errors:
    missing_required_param: error
    dead_code: error
    prefer_final_locals: error
    avoid_print: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    empty_statements: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    prefer_void_to_null: error
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_shadowing_type_parameters: error
    avoid_void_async: error
    join_return_with_assignment: error
    list_remove_unrelated_type: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_interpolation_to_compose_strings: error
    unnecessary_await_in_return: error
    unnecessary_string_interpolations: error
    omit_local_variable_types: error
    deprecated_member_use: error
    unnecessary_new: error
    unnecessary_this: error
    prefer_collection_literals: error
    must_be_immutable: error
    unused_local_variable: error
    prefer_is_empty: error
    unawaited_futures: error
    unused_import: error
    prefer_final_fields: error
    unnecessary_null_in_if_null_operators: error
    override_on_non_overriding_member: error